# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - run: echo ::set-env name=PULL_NUMBER::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
      shell: bash
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.7
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file: :
    - name: 'Create settings.xml'
      uses: whelk-io/maven-settings-xml-action@v4
      with:
        servers: '[{"id": "github-dp3t-shared", "username": "${{ github.actor }}", "password": "${{ github.token}}"}]'
        repositories: '[{"id" : "github-dp3t-shared", "url" : "https://maven.pkg.github.com/DP-3T/dp3t-shared-backend"}]'
    - name: Build with Maven
      run: |
        mvn install --file dpppt-backend-shared/pom.xml;
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TESTCONTAINERS_RYUK_DISABLED: true
    - name: Publish to GitHub Packages Apache Maven
      if: github.ref == 'refs/heads/develop'
      run: mvn deploy -Dmaven.test.skip=true --file dpppt-backend-shared/pom.xml -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: shasum
      run: shasum -a 256 dpppt-backend-shared/target/dpppt-backend-shared.jar > dpppt-backend-shared/target/dpppt-backend-shared.sha256
      shell: bash
    - name: Create Snapshot Release
      uses: ncipollo/release-action@v1
      if: github.ref == 'refs/heads/develop'
      id: create_release
      with:
        name: Snapshot Release ${{ github.ref }}
        tag: SNAPSHOT
        artifacts: "dpppt-backend-shared/target/dpppt-backend-shared.jar,dpppt-backend-shared/target/dpppt-backend-shared.sha256"
        body: |
            Changes in this Release
            - Snapshot release
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
        allowUpdates: true
